linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/spf13/viper

linters:
    enable-all: true
    disable:
        - funlen
        - maligned

        # TODO: fix me
        - whitespace
        - deadcode
        - unused
        - wsl
        - golint
        - stylecheck
        - gochecknoinits
        - misspell
        - gosimple
        - gochecknoglobals
        - errcheck
        - lll
        - godox
        - scopelint
        - gocyclo
        - gocognit
        - gocritic