go_import_path: github.com/spf13/viper

language: go
go:
  - 1.5.4
  - 1.6.3
  - 1.7
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go install ./...
  - go test -v ./...

after_success:
  - go get -u -d github.com/spf13/hugo
  - cd $GOPATH/src/github.com/spf13/hugo && make && ./hugo -s docs && cd -

sudo: false
