name: Octoslash

on: issue_comment

permissions:
  issues: write
  # pull-requests: write

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Octoslash
        uses: sagikazarmark/octoslash-action@v0
